### ISSUE TITLE
Consider adding ultra sound relay

### ISSUE THREAD

**Issue by JustinDrake** [ponkila/nixobolus#15]
The ultra sound relay is available at `https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money`. As a side note, `relayooor.wtf` is no longer operating.

https://github.com/ponkila/nixobolus/blob/c492354792a6bb5f73a3125ba53bd2f5b19cbd65/flake.nix#L443-L451

**Comment by tupakkatapa** [comment]
Thank you for the advice. Closed by #16
